export type HotlistPlatform = {
  id: string
  title: string
  subtitle?: string
}

/** 主面板 30 个平台（与参考图一致） */
const PRIMARY_PLATFORMS: HotlistPlatform[] = [
  { id: 'xiaohongshu', title: '小红书', subtitle: '热搜榜' },
  { id: 'github', title: 'GitHub', subtitle: 'Trending' },
  { id: 'zhihu', title: '知乎', subtitle: '热榜' },
  { id: 'weibo', title: '微博', subtitle: '热搜榜' },
  { id: 'sspai', title: '少数派', subtitle: '热门' },
  { id: 'baidu', title: '百度', subtitle: '热搜榜' },
  { id: 'douyin', title: '抖音', subtitle: '热榜' },
  { id: 'follow', title: '关注的最新动态' },
  { id: 'v2ex', title: 'V2EX', subtitle: '热议' },
  { id: 'hupu', title: '虎扑', subtitle: '步行街' },
  { id: 'sina', title: '新浪网', subtitle: '热榜' },
  { id: 'thepaper', title: '澎湃新闻', subtitle: '热榜' },
  { id: 'ithome', title: 'IT之家', subtitle: '热榜' },
  { id: 'fund', title: '天天基金', subtitle: '排行' },
  { id: 'xueqiu', title: '雪球', subtitle: '热股' },
  { id: 'woshipm', title: '人人都是产品经理', subtitle: '热榜' },
  { id: 'toutiao-dev', title: '开发者头条', subtitle: '热门' },
  { id: '52pojie', title: '吾爱破解论坛', subtitle: '热帖' },
  { id: 'geekpark', title: '极客公园', subtitle: '热点' },
  { id: '36kr', title: '36氪', subtitle: '热榜' },
  { id: 'ifanr', title: '爱范儿', subtitle: '热门' },
  { id: 'huxiu', title: '虎嗅', subtitle: '24小时' },
  { id: 'livesino', title: 'LiveSino', subtitle: '最新' },
  { id: '36kr-column', title: '36氪专栏' },
  { id: 'frontend-weekly', title: '前端周刊', subtitle: '精选' },
  { id: 'guozifang', title: '菓子坊', subtitle: '最新' },
  { id: 'liancaier', title: '恋采儿', subtitle: '最新' },
  { id: 'ai-dict', title: 'AI-DICT', subtitle: '资讯' },
  { id: 'panews', title: 'PANews深度资讯' },
  { id: 'everywhere', title: 'Everywhere', subtitle: '开发者' },
]

/** 未订阅扩展平台（截图 70+ 项） */
const EXTENDED_PLATFORMS: HotlistPlatform[] = [
  { id: 'douban-group', title: '豆瓣社区', subtitle: '热点·话题' },
  { id: 'landian', title: '蓝点网', subtitle: '软件·资讯' },
  { id: 'topys', title: 'TOPYS', subtitle: '创意·设计' },
  { id: 'nba', title: 'NBA', subtitle: '篮球·最新动态' },
  { id: 'douban-movie', title: '豆瓣电影', subtitle: '正在上映·口碑' },
  { id: 'newsmth', title: '水木社区', subtitle: '高教·校园' },
  { id: 'oschina', title: '开源中国', subtitle: '开发者·生态' },
  { id: 'tencent', title: '腾讯', subtitle: '综合·资讯' },
  { id: 'csdn', title: 'CSDN', subtitle: '开发者社区' },
  { id: 'pangniu', title: '胖妞网', subtitle: '社区·资讯' },
  { id: 'bazu', title: '霸主', subtitle: '社区·热点' },
  { id: 'cyzone', title: '创业邦', subtitle: '创投·列表' },
  { id: 'douban-book', title: '豆瓣读书', subtitle: '阅读·榜单' },
  { id: 'deepconnect', title: '深度互联', subtitle: '科技·深度' },
  { id: 'qiushi', title: '求是网', subtitle: '时政·理论' },
  { id: 'xinhua-book', title: '新华读书', subtitle: '阅读·推荐' },
  { id: 'zhihu-daily', title: '知乎日报', subtitle: '每日·精选' },
  { id: 'qike', title: '奇客网', subtitle: '极客·前沿' },
  { id: 'toutiao', title: '今日头条', subtitle: '资讯·热点' },
  { id: 'jiemian', title: '界面新闻', subtitle: '财经·商业' },
  { id: 'bing', title: '必应搜索', subtitle: '搜索·热点' },
  { id: 'taisha', title: '太傻新闻', subtitle: '社区·资讯' },
  { id: 'cri-online', title: '国际在线', subtitle: '国际·频道' },
  { id: 'football-rank', title: '足球排行榜', subtitle: '体育·足球' },
  { id: 'football-score', title: '足球比分网', subtitle: '体育·比分' },
  { id: 'basketball', title: '篮球综合', subtitle: '体育·篮球' },
  { id: 'takungpao', title: '大公网', subtitle: '时事·深度' },
  { id: 'guangming', title: '光明网', subtitle: '时政·资讯' },
  { id: 'huaban', title: '花瓣网', subtitle: '灵感·社区' },
  { id: 'jandan', title: '煎蛋', subtitle: '趣味·段子' },
  { id: 'quanli', title: '圈里那些事', subtitle: '社区·话题' },
  { id: 'acfun', title: 'A站', subtitle: '弹幕·视频' },
  { id: 'tencent-video', title: '腾讯视频', subtitle: '影视·热播' },
  { id: 'rayli', title: '瑞丽女性', subtitle: '时尚·生活' },
  { id: 'letv', title: '乐视视频', subtitle: '影视·资讯' },
  { id: 'campus-movies', title: '校园电影', subtitle: '影视·校园' },
  { id: 'bilibili', title: 'B站', subtitle: '视频·二次元' },
  { id: 'dytt', title: '电影天堂', subtitle: '经典·怀旧' },
  { id: 'qq-music', title: 'QQ音乐', subtitle: '音乐·热歌' },
  { id: 'netease-music', title: '网易云音乐', subtitle: '音乐·旋律' },
  { id: 'kugou', title: '酷狗音乐', subtitle: '音乐·海量' },
  { id: 'apple-music', title: 'Apple Music', subtitle: '音乐·品质' },
  { id: 'dzfinance', title: '大众金融数据', subtitle: '财经·数据' },
  { id: 'smzdm', title: '值得买', subtitle: '购物·攻略' },
  { id: 'sohu', title: '搜狐', subtitle: '综合·新闻' },
  { id: 'baidu-news', title: '百度资讯', subtitle: '资讯·热点' },
  { id: 'movie-bus', title: '电影巴士', subtitle: '影视·资讯' },
  { id: 'lol', title: '英雄联盟', subtitle: '游戏·电竞' },
  { id: 'vgtime', title: 'VGTime', subtitle: '游戏·生活' },
  { id: 'thisissports', title: '这就是竞技', subtitle: '体育·竞技' },
  { id: 'jump', title: 'Jump项目', subtitle: '游戏·Switch' },
  { id: 'thisismonday', title: '这就是周一', subtitle: '资讯·周刊' },
  { id: 'novel-community', title: '小说社区', subtitle: '阅读·社区' },
  { id: 'novel-list', title: '小说列表', subtitle: '阅读·榜单' },
  { id: 'psn', title: 'PSN游戏列表', subtitle: '主机·竞技' },
  { id: 'ign-china', title: 'IGN中国', subtitle: '游戏·动漫' },
  { id: 'autohome', title: '汽车之家', subtitle: '汽车·生活' },
  { id: 'xcar', title: '爱卡汽车', subtitle: '汽车·摄影' },
  { id: 'pcauto', title: '太平洋汽车', subtitle: '汽车·社区' },
  { id: 'gamersky', title: '游民星空', subtitle: '游戏·攻略' },
  { id: 'xueqiu-insight', title: '雪球内参', subtitle: '投资·理财' },
  { id: 'jrj', title: '金融界', subtitle: '金融·理财' },
  { id: 'wallstreetcn', title: '华尔街见闻', subtitle: '金融·资讯' },
  { id: 'huima', title: '绘马', subtitle: '社区·资讯' },
  { id: 'finance-live', title: '财经实时榜', subtitle: '财经·实时' },
  { id: 'finance-market', title: '财经行情', subtitle: '财经·行情' },
  { id: 'zaker', title: 'ZAKER', subtitle: '聚合·阅读' },
  { id: 'computer-paper', title: '电脑报', subtitle: '数码·手机' },
  { id: 'netease-news', title: '网易新闻', subtitle: '头条·资讯' },
  { id: 'tieba', title: '百度贴吧', subtitle: '热议榜' },
  { id: 'kuaishou', title: '快手', subtitle: '热榜' },
  { id: 'juejin', title: '掘金', subtitle: '开发者·成长' },
  { id: 'coolapk', title: '酷安', subtitle: '数码·热榜' },
  { id: 'ngabbs', title: 'NGA', subtitle: '游戏·社区' },
  { id: 'jianshu', title: '简书', subtitle: '创作·热门' },
  { id: 'guokr', title: '果壳', subtitle: '科普·热门' },
  { id: 'yystv', title: '游研社', subtitle: '游戏·文化' },
  { id: 'hellogithub', title: 'HelloGitHub', subtitle: '开源·推荐' },
]

export const HOTLIST_PLATFORMS: HotlistPlatform[] = [...PRIMARY_PLATFORMS, ...EXTENDED_PLATFORMS]

export const HOTLIST_AGGREGATOR_ALIASES: Record<string, string[]> = {
  follow: ['guokr', 'zhihu-daily'],
  'toutiao-dev': ['juejin', 'toutiao'],
  '36kr-column': ['36kr'],
  guozifang: ['guokr'],
  liancaier: ['sspai'],
  'ai-dict': ['juejin'],
  everywhere: ['hellogithub', 'github'],
  baidu: ['baidu'],
  zhihu: ['zhihu'],
  v2ex: ['v2ex'],
  hupu: ['hupu'],
  sina: ['sina'],
  thepaper: ['thepaper'],
  '36kr': ['36kr'],
  huxiu: ['huxiu'],
  xueqiu: ['xueqiu'],
  xiaohongshu: ['xiaohongshu'],
  geekpark: ['36kr', 'geekpark'],
  woshipm: ['woshipm'],
  'douban-group': ['douban-group'],
  'douban-movie': ['douban-movie'],
  'douban-book': ['douban-movie'],
  newsmth: ['newsmth'],
  oschina: ['csdn', 'oschina'],
  tencent: ['qq-news', 'tencent'],
  csdn: ['csdn'],
  qike: ['geekpark', '36kr'],
  toutiao: ['toutiao'],
  jiemian: ['36kr', 'thepaper'],
  bing: ['baidu'],
  acfun: ['acfun'],
  bilibili: ['bilibili'],
  smzdm: ['smzdm'],
  sohu: ['sina'],
  'baidu-news': ['baidu'],
  lol: ['lol'],
  gamersky: ['gameres', 'gamersky'],
  'xueqiu-insight': ['xueqiu'],
  wallstreetcn: ['wallstreetcn'],
  'netease-news': ['netease-news'],
  tieba: ['tieba'],
  kuaishou: ['kuaishou'],
  juejin: ['juejin'],
  coolapk: ['coolapk'],
  ngabbs: ['ngabbs'],
  jianshu: ['jianshu'],
  guokr: ['guokr'],
  yystv: ['yystv'],
  hellogithub: ['hellogithub'],
  'zhihu-daily': ['zhihu-daily'],
  ifanr: ['ifanr'],
  '52pojie': ['52pojie'],
  landian: ['ithome', 'landian'],
  topys: ['sspai', 'topys'],
  nba: ['nba', 'hupu'],
  cyzone: ['36kr', 'cyzone'],
  deepconnect: ['36kr', 'huxiu'],
  qiushi: ['sina', 'thepaper'],
  'xinhua-book': ['zhihu-daily', 'douban-movie'],
  taisha: ['v2ex', 'jianshu'],
  'cri-online': ['netease-news', 'sina'],
  'football-rank': ['hupu', 'nba'],
  'football-score': ['hupu'],
  basketball: ['hupu', 'nba'],
  takungpao: ['sina', 'thepaper'],
  guangming: ['sina', 'thepaper'],
  huaban: ['xiaohongshu', 'coolapk'],
  quanli: ['weibo', 'douban-group'],
  'tencent-video': ['bilibili', 'douyin'],
  rayli: ['weibo', 'xiaohongshu'],
  letv: ['bilibili', 'douyin'],
  'campus-movies': ['douban-movie', 'bilibili'],
  dytt: ['douban-movie', 'bilibili'],
  'qq-music': ['netease-music', 'qq-music'],
  'netease-music': ['netease-music'],
  kugou: ['kugou', 'netease-music'],
  'apple-music': ['netease-music'],
  dzfinance: ['xueqiu', 'wallstreetcn'],
  'movie-bus': ['douban-movie', 'bilibili'],
  vgtime: ['yystv', 'gamersky'],
  thisissports: ['hupu', 'nba'],
  jump: ['ngabbs', 'gamersky'],
  thisismonday: ['36kr', 'sspai'],
  'novel-community': ['jianshu', 'zhihu'],
  'novel-list': ['jianshu', 'douban-book'],
  psn: ['gamersky', 'ngabbs'],
  'ign-china': ['gamersky', 'yystv'],
  autohome: ['autohome', 'coolapk'],
  xcar: ['autohome', 'coolapk'],
  pcauto: ['autohome', 'coolapk'],
  jrj: ['wallstreetcn', 'xueqiu'],
  huima: ['v2ex', 'jianshu'],
  'finance-live': ['xueqiu', 'wallstreetcn'],
  'finance-market': ['xueqiu', 'wallstreetcn'],
  zaker: ['netease-news', 'toutiao'],
  'computer-paper': ['ithome', 'coolapk'],
  pangniu: ['v2ex', 'jianshu'],
  bazu: ['tieba', 'ngabbs'],
}

export const HOTLIST_RSS_SOURCES: Record<string, string> = {
  livesino: 'https://livesino.net/feed',
  'frontend-weekly': 'https://frontendweekly.cn/feeds/rss.xml',
  panews: 'https://www.panewslab.com/zh/rss.xml',
  '36kr-column': 'https://36kr.com/feed-column',
  ifanr: 'https://www.ifanr.com/feed',
  geekpark: 'https://www.geekpark.net/rss',
  everywhere: 'https://everywhere.app/rss.xml',
  oschina: 'https://www.oschina.net/news/rss',
  jandan: 'https://jandan.net/rss',
  landian: 'https://www.landiannews.com/feed',
  topys: 'https://www.topys.cn/rss/all.rss',
  cyzone: 'https://www.cyzone.cn/rss',
  qike: 'https://www.geekpark.net/rss',
  huxiu: 'https://www.huxiu.com/rss/0.xml',
  deepconnect: 'https://www.huxiu.com/rss/0.xml',
  woshipm: 'https://www.woshipm.com/feed',
  'cri-online': 'https://news.cri.cn/rss/china.xml',
  takungpao: 'https://www.takungpao.com/rss/news.xml',
  guangming: 'https://www.gmw.cn/rss/rss.xml',
  rayli: 'https://www.rayli.com.cn/rss.xml',
  vgtime: 'https://www.vgtime.com/rss.jhtml',
  'ign-china': 'https://www.ign.com.cn/rss',
  autohome: 'https://www.autohome.com.cn/rss/',
  gamersky: 'https://www.gamersky.com/rss/news.xml',
  zaker: 'https://app.myzaker.com/rss.php',
  'computer-paper': 'https://www.weixinyunduan.com/rss/weixinyunduan.xml',
}
